### ISSUE TITLE
read github org from config

### ISSUE THREAD

**Issue by frosty-geek** [SovereignCloudStack/github-manager#100]
https://github.com/SovereignCloudStack/github-manager/blob/9556bd8114b7f73c830e6dca8f5f8cd5f26964e7/check_repositories.py#L6

**Comment by itrich** [comment]
Does your feature request involve that we should use the environment variable `ORGANIZATION` throughout all of our GitHub Action workflows?

**Comment by frosty-geek** [comment]
maybe I misread the code, I asumed that this means that SovereignCloudStack is hardcoded in the code.

**Comment by itrich** [comment]
The letter is only a fallback if `ORGANIZATION` is not defined as environment variable.
