### ISSUE TITLE
Add missing repositories

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/github-manager#24]
There have been created some repositories recently. We should add those to oure github-manager to streamline them with our gitops approach.

**Comment by itrich** [comment]
IMHO there should be a tool to find all repositories that aren't covered by the `github-manager`.
@tibeer Didn't you write some handy python lines to get this information?

**Comment by tibeer** [comment]
nope, i just wrote something to gather information if the primary branch is still named "master" I guess. Currently we handle this manually.

**Comment by itrich** [comment]
Replaced by https://github.com/SovereignCloudStack/issues/issues/256
