### ISSUE TITLE
Adding a new member fails if invitee is added to a team in the same run

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/github-manager#51]
If a new community member is added via `github-manager` and that invitee is added to a team at the same time, the CI run will fail als it can't add the new member (which hasn't yet accepted the invite) to the particular team.

The run should not fail in this case and just retry to add the new member to it's team in the next run.

**Comment by tibeer** [comment]
This generates some more difficulties as this is partly out of scope of the opentelekomcloud/ansible-collection-gitcontrol . It only assures a certain state which cannot depend on acceptance of invitations. One possible solution would be to have the playbook run executed periodically besides executions triggered trough merges. Therefore started an upstream discussion how to deal with such cases.

**Comment by tibeer** [comment]
@itrich did the same on my test project. Added a new user while also adding the user to a group. Had no issues. Instead, the user is shown as pending when it comes to group association. I guess we need to have a session again diffing both orgs.

**Comment by itrich** [comment]
> @itrich did the same on my test project. Added a new user while also adding the user to a group. Had no issues. Instead, the user is shown as pending when it comes to group association. I guess we need to have a session again diffing both orgs.

I'm referring to this failed run: https://github.com/SovereignCloudStack/github-manager/actions/runs/3335359806/jobs/5519250070

But maybe this is related to something completely different, e.g. the renaming of @manuela-urban? Let's fix #53 first and have a look at this issue again.

**Comment by tibeer** [comment]
Closes as this cannot be reproduced currently. Once this issue reappears we will create a new issue for this.
