### ISSUE TITLE
github-manager should allow to deactivate notifications

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/github-manager#77]
Currently github-manager reenables notifications for me, even if I deactivated them for certain projects.
It would be good, if we teach github manager that one can opt out of certain repos through its configuration.

**Comment by itrich** [comment]
Strange! I'll have a look at this. I wasn't even aware that changing the metadata of a repository also changes notification behaviour.

**Comment by itrich** [comment]
I couldn't reproduce this behaviour. Could you please describe what you're exactly doing?

Are you switching the `Watch` settings to `Ignore` and that configuration is being changed upon invoking `github-manager`. This wasn't the case as for me as I just tested.... :thinking:

**Comment by fkr** [comment]
I tried again as well and can’t reproduce it either anylonger. Will close the issue and just re-open if it surfaces again. 
Thanks and sorry for the noise.
